/* Generated by AN DISI Unibo */ 
package it.unibo.robot

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Robot ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("robot init")
					}
					 transition(edgeName="t00",targetState="move",cond=whenRequest("moveTo"))
				}	 
				state("move") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveTo(OldX,OldY,X,Y)"), Term.createTerm("moveTo(A,B,X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val X = payloadArg(2)
												val Y = payloadArg(3)
								answer("moveTo", "moveOk", "moveOk($X,$Y)"   )  
						}
					}
					 transition(edgeName="t01",targetState="move",cond=whenRequest("moveTo"))
				}	 
			}
		}
}
