/* Generated by AN DISI Unibo */ 
package it.unibo.robot

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Robot ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				var CurrentPlannedMove = ""
				val mapname                    = "teaRoomExplored"
				var Started			            = false
		//		val StepTime                   = 600L //firefox f11 on laptop registrazione
		//		val StepTime                   = 800L //firefox f11 on monitor registrazione
		//		val StepTime                   = 600L //firefox f11 on monitor no registrazione
				var X = ""
				var Y = ""
				var Debug = false
				var StepTime = 500L
				var StepFailWaitTime = 5000L
				var Fails = 1
				var StepFailTime = 150L
				var LastTurn = ""
				val Name = name
				val MapTopic = "unibo/qak/robot/map"
				val ControlTopic = "unibo/qak/robot/control"
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("robot init")
						solve("consult('tearoomKB-project-sprint3.pl')","") //set resVar	
						solve("stepTime(X)","") //set resVar	
						if( currentSolution.isSuccess() ) { StepTime = getCurSol("X").toString().toLong()  
						println("robot StepTime = $StepTime")
						}
						else
						{}
						solve("stepFailWaitTime(X)","") //set resVar	
						if( currentSolution.isSuccess() ) { StepFailWaitTime = getCurSol("X").toString().toLong()  
						println("robot StepFailWaitTime = $StepFailWaitTime")
						}
						else
						{}
						solve("debug($Name,true)","") //set resVar	
						if( currentSolution.isSuccess() ) { Debug = true  
						println("robot Debug = $Debug")
						}
						else
						{}
						itunibo.planner.plannerUtil.initAI(  )
						itunibo.planner.plannerUtil.loadRoomMap( mapname  )
						 val Map = itunibo.planner.plannerUtil.getMapHTML()  
						 publish(Map, MapTopic)  
						updateResourceRep( "robot(${itunibo.planner.plannerUtil.getPosX()},${itunibo.planner.plannerUtil.getPosY()},${itunibo.planner.plannerUtil.getDir().toString()})"  
						)
					}
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
				state("waitRequest") { //this:State
					action { //it:State
						 publish("Robot automatically controlled, press to switch to manual", ControlTopic)  
					}
					 transition(edgeName="t02",targetState="waitRequest",cond=whenDispatch("stopPlan"))
					transition(edgeName="t03",targetState="manualControl",cond=whenDispatch("manual"))
					transition(edgeName="t04",targetState="planForMoves",cond=whenRequest("moveTo"))
				}	 
				state("manualControl") { //this:State
					action { //it:State
						 publish("Robot manually controlled, press to switch to auto", ControlTopic)  
						 val Map = itunibo.planner.plannerUtil.getMapHTML()  
						 publish(Map, MapTopic)  
					}
					 transition(edgeName="t05",targetState="waitRequest",cond=whenDispatch("manual"))
				}	 
				state("planForMoves") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveTo(X,Y)"), Term.createTerm("moveTo(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												X = payloadArg(0)
												Y = payloadArg(1)
												itunibo.planner.plannerUtil.planForGoal(X,Y)
						}
						stateTimer = TimerActor("timer_planForMoves", 
							scope, context!!, "local_tout_robot_planForMoves", 200.toLong() )
					}
					 transition(edgeName="t06",targetState="execPlannedMoves",cond=whenTimeout("local_tout_robot_planForMoves"))   
					transition(edgeName="t07",targetState="replyKo",cond=whenDispatch("stopPlan"))
				}	 
				state("execPlannedMoves") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stepdone(V)"), Term.createTerm("stepdone(A)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  Fails > 1  
								 ){forward("cmd", "cmd(s)" ,"basicrobot" ) 
								delay(50) 
								forward("cmd", "cmd(h)" ,"basicrobot" ) 
								delay(50) 
								}
								 Fails = 1  
								itunibo.planner.plannerUtil.updateMap( CurrentPlannedMove, ""  )
								 val Map = itunibo.planner.plannerUtil.getMapHTML()  
								 publish(Map, MapTopic)  
						}
						updateResourceRep( "robot(${itunibo.planner.plannerUtil.getPosX()},${itunibo.planner.plannerUtil.getPosY()},${itunibo.planner.plannerUtil.getDir().toString()})"  
						)
						 CurrentPlannedMove = itunibo.planner.plannerUtil.getNextPlannedMove()  
						stateTimer = TimerActor("timer_execPlannedMoves", 
							scope, context!!, "local_tout_robot_execPlannedMoves", 100.toLong() )
					}
					 transition(edgeName="t08",targetState="maybeExecTheMove",cond=whenTimeout("local_tout_robot_execPlannedMoves"))   
					transition(edgeName="t09",targetState="replyKo",cond=whenDispatch("stopPlan"))
				}	 
				state("maybeExecTheMove") { //this:State
					action { //it:State
						if(  CurrentPlannedMove.length == 0  
						 ){answer("moveTo", "moveOk", "moveOk($X,$Y)"   )  
						}
					}
					 transition( edgeName="goto",targetState="execTheMove", cond=doswitchGuarded({ CurrentPlannedMove.length > 0  
					}) )
					transition( edgeName="goto",targetState="waitRequest", cond=doswitchGuarded({! ( CurrentPlannedMove.length > 0  
					) }) )
				}	 
				state("execTheMove") { //this:State
					action { //it:State
						if(  CurrentPlannedMove == "w"  
						 ){request("step", "step($StepTime)" ,"basicrobot" )  
						}
						else
						 {forward("cmd", "cmd($CurrentPlannedMove)" ,"basicrobot" ) 
						 itunibo.planner.plannerUtil.updateMap( CurrentPlannedMove, ""  )
						  val Map = itunibo.planner.plannerUtil.getMapHTML()  
						  publish(Map, MapTopic)  
						  LastTurn = CurrentPlannedMove  
						 delay(300) 
						 }
					}
					 transition( edgeName="goto",targetState="execPlannedMoves", cond=doswitchGuarded({ CurrentPlannedMove != "w"  
					}) )
					transition( edgeName="goto",targetState="waitStepReply", cond=doswitchGuarded({! ( CurrentPlannedMove != "w"  
					) }) )
				}	 
				state("waitStepReply") { //this:State
					action { //it:State
					}
					 transition(edgeName="t010",targetState="execPlannedMoves",cond=whenReply("stepdone"))
					transition(edgeName="t011",targetState="handleStepFailure",cond=whenReply("stepfail"))
				}	 
				state("handleStepFailure") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stepfail(DURATION,CAUSE)"), Term.createTerm("stepfail(D,C)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("cmd", "cmd(s)" ,"basicrobot" ) 
								delay((Fails++) * StepFailTime ) 
								forward("cmd", "cmd(h)" ,"basicrobot" ) 
								delay(50) 
								
									    		val NewX = itunibo.planner.plannerUtil.get_curPos().first
									    		val NewY = itunibo.planner.plannerUtil.get_curPos().second
								answer("moveTo", "moveKo", "moveKo($NewX,$NewY)"   )  
						}
					}
					 transition( edgeName="goto",targetState="handleFailRebounce", cond=doswitchGuarded({ Fails > ((StepTime / StepFailTime) + 1)  
					}) )
					transition( edgeName="goto",targetState="waitRequest", cond=doswitchGuarded({! ( Fails > ((StepTime / StepFailTime) + 1)  
					) }) )
				}	 
				state("handleFailRebounce") { //this:State
					action { //it:State
						 if(LastTurn == "l") {  
						forward("cmd", "cmd(r)" ,"basicrobot" ) 
						delay(400) 
						forward("cmd", "cmd(s)" ,"basicrobot" ) 
						delay(150) 
						forward("cmd", "cmd(h)" ,"basicrobot" ) 
						delay(50) 
						forward("cmd", "cmd(l)" ,"basicrobot" ) 
						 } else if(LastTurn == "r") {  
						forward("cmd", "cmd(l)" ,"basicrobot" ) 
						delay(400) 
						forward("cmd", "cmd(s)" ,"basicrobot" ) 
						delay(150) 
						forward("cmd", "cmd(h)" ,"basicrobot" ) 
						delay(50) 
						forward("cmd", "cmd(r)" ,"basicrobot" ) 
						 }  
					}
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
				state("replyKo") { //this:State
					action { //it:State
						 val NewX = itunibo.planner.plannerUtil.get_curPos().first
							       val NewY = itunibo.planner.plannerUtil.get_curPos().second  
						answer("moveTo", "moveKo", "moveKo($NewX,$NewY)"   )  
					}
					 transition( edgeName="goto",targetState="waitRequest", cond=doswitch() )
				}	 
			}
		}
}
