/* Generated by AN DISI Unibo */ 
package it.unibo.waiter

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Waiter ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var MaxStayTime 	= 100000L	
				val DelayTime 		= 1000L
				val CleanDelayTime 	= 4000L
				val RestWaitTime 	= 10000L
				var CurrentCid		= ""
				val Name = name
				var Debug = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = false
						solve("consult('tearoomKB-project-sprint3.pl')","") //set resVar	
						solve("debug($Name,true)","") //set resVar	
						if( currentSolution.isSuccess() ) { Debug = true  
						}
						else
						{}
						solve("maxStayTime(X)","") //set resVar	
						if( currentSolution.isSuccess() ) { MaxStayTime = getCurSol("X").toString().toLong()  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("waitState") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_waitState", 
							scope, context!!, "local_tout_waiter_waitState", 100.toLong() )
					}
					 transition(edgeName="t019",targetState="checkDirtyTable",cond=whenTimeout("local_tout_waiter_waitState"))   
					transition(edgeName="t020",targetState="getPayment",cond=whenDispatch("payment"))
					transition(edgeName="t021",targetState="checkClientTime",cond=whenDispatch("timeexpired"))
					transition(edgeName="t022",targetState="checkTableAvail",cond=whenRequest("table"))
					transition(edgeName="t023",targetState="reach",cond=whenDispatch("clientatentrance"))
					transition(edgeName="t024",targetState="takeOrder",cond=whenDispatch("placeorder"))
					transition(edgeName="t025",targetState="serveOrder",cond=whenReply("orderready"))
					transition(edgeName="t026",targetState="thinkCleanTable",cond=whenDispatch("cleantable"))
				}	 
				state("checkTableAvail") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("table(CID)"), Term.createTerm("table(Cid)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentCid = payloadArg(0)  
								solve("updateWaiterState(X,checkAvailability($CurrentCid))","") //set resVar	
								solve("occupyHall($CurrentCid)","") //set resVar	
								solve("reserveTable(Num,$CurrentCid)","") //set resVar	
								if( currentSolution.isSuccess() ) {answer("table", "available", "available($CurrentCid)"   )  
								forward("clientatentrance", "clientatentrance($CurrentCid)" ,"waiter" ) 
								}
								else
								{answer("table", "full", "full($CurrentCid,$MaxStayTime)"   )  
								solve("assert(client($CurrentCid,onhold))","") //set resVar	
								}
						}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("reach") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("clientatentrance(Cid)"), Term.createTerm("clientatentrance(CurrentCid)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentCid = payloadArg(0)  
								solve("updateWaiterState(X,reachfor($CurrentCid))","") //set resVar	
						}
						solve("coordinatesTo(entrancedoor,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()		 
						request("moveTo", "moveTo($X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition(edgeName="t027",targetState="reachp2",cond=whenReply("moveOk"))
					transition(edgeName="t028",targetState="reach",cond=whenReply("moveKo"))
				}	 
				state("reachp2") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("freeHall($CurrentCid)","") //set resVar	
								solve("updateClient($CurrentCid,entering)","") //set resVar	
								solve("updateWaiterState(X,reached($CurrentCid))","") //set resVar	
						}
						solve("teatable(Num,reserved($CurrentCid),clean)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("coordinatesTo(teatable($TableNum),X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()		 
						request("moveTo", "moveTo($X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition(edgeName="t029",targetState="reachp3",cond=whenReply("moveOk"))
					transition(edgeName="t030",targetState="reachp2",cond=whenReply("moveKo"))
				}	 
				state("reachp3") { //this:State
					action { //it:State
						solve("teatable(Num,reserved($CurrentCid),clean)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("updateWaiterState(X,deployed($CurrentCid))","") //set resVar	
						solve("engageTable($TableNum,$CurrentCid)","") //set resVar	
						emit("attable", "attable($CurrentCid)" ) 
						solve("updateClient($CurrentCid,choosing)","") //set resVar	
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("takeOrder") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("placeorder(CID)"), Term.createTerm("placeorder(CurrentCid)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentCid = payloadArg(0)  
								solve("updateWaiterState(X,goTakeOrder($CurrentCid))","") //set resVar	
								solve("updateClient($CurrentCid,placeorder)","") //set resVar	
						}
						solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("coordinatesTo(teatable($TableNum),X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()		 
						request("moveTo", "moveTo($X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition(edgeName="t031",targetState="takeOrderp2",cond=whenReply("moveOk"))
					transition(edgeName="t032",targetState="takeOrder",cond=whenReply("moveKo"))
				}	 
				state("takeOrderp2") { //this:State
					action { //it:State
						solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("updateWaiterState(X,takingOrder($CurrentCid))","") //set resVar	
						solve("updateClient($CurrentCid,orderplaced)","") //set resVar	
						request("relayorder", "relayorder($CurrentCid)" ,"barman" )  
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("serveOrder") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("orderready(Cid)"), Term.createTerm("orderready(CurrentCid)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentCid = payloadArg(0)  
								solve("updateWaiterState(X,getOrderReady($CurrentCid))","") //set resVar	
						}
						solve("coordinatesTo(barman,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()	 
						request("moveTo", "moveTo($X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition(edgeName="t033",targetState="serveOrderp2",cond=whenReply("moveOk"))
					transition(edgeName="t034",targetState="serveOrder",cond=whenReply("moveKo"))
				}	 
				state("serveOrderp2") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("updateWaiterState(X,atbar($CurrentCid))","") //set resVar	
						}
						solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("coordinatesTo(teatable($TableNum),X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()  
						request("moveTo", "moveTo($X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition(edgeName="t035",targetState="serveOrderp3",cond=whenReply("moveOk"))
					transition(edgeName="t036",targetState="serveOrderp2",cond=whenReply("moveKo"))
				}	 
				state("serveOrderp3") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
								  val X = payloadArg(0)
												val Y = payloadArg(1)   
												val TableNum = getCurSol("Num").toString()	 
								solve("updateWaiterState(X,serving($CurrentCid))","") //set resVar	
								solve("updateClient($CurrentCid,consuming)","") //set resVar	
								emit("delivered", "delivered($CurrentCid)" ) 
								 forwardWithDelay("timeexpired", "timeexpired($CurrentCid)", "waiter", MaxStayTime)  
						}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("checkClientTime") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("timeexpired(Cid)"), Term.createTerm("timeexpired(Cid)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val CurrentCid = payloadArg(0)  
								solve("client($CurrentCid,consuming)","") //set resVar	
								if( currentSolution.isSuccess() ) {forward("payment", "payment($CurrentCid)" ,"waiter" ) 
								}
								else
								{}
						}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("getPayment") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("payment(Cid)"), Term.createTerm("payment(CurrentCid)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentCid = payloadArg(0)  
						}
						solve("client($CurrentCid,consuming)","") //set resVar	
						if( currentSolution.isSuccess() ) {}
						else
						{ CurrentCid = ""  
						}
					}
					 transition( edgeName="goto",targetState="getPaymentp1", cond=doswitchGuarded({ CurrentCid != ""  
					}) )
					transition( edgeName="goto",targetState="waitState", cond=doswitchGuarded({! ( CurrentCid != ""  
					) }) )
				}	 
				state("getPaymentp1") { //this:State
					action { //it:State
						solve("updateWaiterState(X,getPayment($CurrentCid))","") //set resVar	
						solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("coordinatesTo(teatable($TableNum),X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()		 
						request("moveTo", "moveTo($X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition(edgeName="t037",targetState="getPaymentp2",cond=whenReply("moveOk"))
					transition(edgeName="t038",targetState="getPaymentp1",cond=whenReply("moveKo"))
				}	 
				state("getPaymentp2") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
								 val TableNum = getCurSol("Num").toString()  
								solve("updateWaiterState(X,paymentOf($CurrentCid))","") //set resVar	
								solve("updateClient($CurrentCid,paying)","") //set resVar	
								delay(2000) 
								solve("freeTable($TableNum,$CurrentCid)","") //set resVar	
								emit("paymentOk", "paymentOk($CurrentCid)" ) 
								solve("updateClient($CurrentCid,leaving)","") //set resVar	
								solve("updateWaiterState(X,escorting($CurrentCid))","") //set resVar	
								forward("cleantable", "cleantable($TableNum)" ,"waiter" ) 
						}
						solve("coordinatesTo(exitdoor,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  
										val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()
						request("moveTo", "moveTo($X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition(edgeName="t039",targetState="escortToExit",cond=whenReply("moveOk"))
					transition(edgeName="t040",targetState="getPaymentp2",cond=whenReply("moveKo"))
				}	 
				state("escortToExit") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								emit("exitOk", "exitOk($CurrentCid)" ) 
								solve("updateWaiterState(X,escorted($CurrentCid))","") //set resVar	
								solve("updateClient($CurrentCid,left)","") //set resVar	
						}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
						delay(500) 
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("thinkCleanTable") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("cleantable(Num)"), Term.createTerm("cleantable(Num)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val TableNum = payloadArg(0)  
								solve("updateWaiterState(X,gocleanteatable($TableNum))","") //set resVar	
								solve("roomstate(S)","") //set resVar	
								println(getCurSol("S").toString())
						}
						solve("waiter(gocleanteatable(Num))","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("coordinatesTo(teatable($TableNum),X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val X = getCurSol("X").toString()
									val Y = getCurSol("Y").toString()		 
						request("moveTo", "moveTo($X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition(edgeName="t041",targetState="cleanTable",cond=whenReply("moveOk"))
					transition(edgeName="t042",targetState="thinkCleanTable",cond=whenReply("moveKo"))
					transition(edgeName="t043",targetState="cancelCurrentPlan",cond=whenRequest("table"))
					transition(edgeName="t044",targetState="cancelCurrentPlan",cond=whenDispatch("clientatentrance"))
					transition(edgeName="t045",targetState="cancelCurrentPlan",cond=whenDispatch("placeorder"))
					transition(edgeName="t046",targetState="cancelCurrentPlan",cond=whenReply("orderready"))
					transition(edgeName="t047",targetState="cancelCurrentPlan",cond=whenDispatch("payment"))
				}	 
				state("cancelCurrentPlan") { //this:State
					action { //it:State
						 autoMsg(currentMsg)  
						forward("stopPlan", "stopPlan(0)" ,"robot" ) 
					}
					 transition(edgeName="t048",targetState="handlePlanCancel",cond=whenReply("moveOk"))
					transition(edgeName="t049",targetState="handlePlanCancel",cond=whenReply("moveKo"))
				}	 
				state("handlePlanCancel") { //this:State
					action { //it:State
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("cleanTable") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								solve("waiter(gocleanteatable(Num))","") //set resVar	
								 val TableNum = getCurSol("Num").toString()  
								solve("updateWaiterState(X,atteatable($TableNum))","") //set resVar	
								solve("roomstate(S)","") //set resVar	
								if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
								)
								}
								else
								{}
								forward("cleantable", "cleantable($TableNum)" ,"waiter" ) 
						}
					}
					 transition(edgeName="t050",targetState="checkTableAvail",cond=whenRequest("table"))
					transition(edgeName="t051",targetState="reach",cond=whenDispatch("clientatentrance"))
					transition(edgeName="t052",targetState="takeOrder",cond=whenDispatch("placeorder"))
					transition(edgeName="t053",targetState="serveOrder",cond=whenReply("orderready"))
					transition(edgeName="t054",targetState="getPayment",cond=whenDispatch("payment"))
					transition(edgeName="t055",targetState="doClean",cond=whenDispatch("cleantable"))
				}	 
				state("doClean") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter doClean")
						 var CurrentTeaTable = ""  
						solve("waiter(atteatable(Num))","") //set resVar	
						if( currentSolution.isSuccess() ) { CurrentTeaTable = getCurSol("Num").toString()  
						}
						else
						{}
						solve("waiter(cleaning(Num))","") //set resVar	
						if( currentSolution.isSuccess() ) { CurrentTeaTable = getCurSol("Num").toString()  
						}
						else
						{}
						solve("waiter(cleaned(Num))","") //set resVar	
						if( currentSolution.isSuccess() ) { CurrentTeaTable = getCurSol("Num").toString()  
						}
						else
						{}
						if( checkMsgContent( Term.createTerm("cleantable(Num)"), Term.createTerm("cleantable($CurrentTeaTable)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("updateWaiterState(X,cleaning($CurrentTeaTable))","") //set resVar	
								delay(CleanDelayTime)
								solve("cleanTable($CurrentTeaTable,NewStatus)","") //set resVar	
								if( currentSolution.isSuccess() ) { val NewStatus = getCurSol("NewStatus").toString()  
								if(  NewStatus == "clean"  
								 ){forward("cleantableok", "cleantableok($CurrentTeaTable)" ,"waiter" ) 
								solve("updateWaiterState(X,cleaned($CurrentTeaTable))","") //set resVar	
								}
								else
								 {forward("cleantable", "cleantable($CurrentTeaTable)" ,"waiter" ) 
								 solve("updateWaiterState(X,cleaning($CurrentTeaTable))","") //set resVar	
								 }
								}
								else
								{}
						}else{
							if( checkMsgContent( Term.createTerm("cleantable(Num)"), Term.createTerm("cleantable(OtherTeaTable)"), 
							                        currentMsg.msgContent()) ) { //set msgArgList
									 forwardWithDelay("cleantable","cleantable(${payloadArg(0)})","waiter",100L)  
							}
						}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition(edgeName="t056",targetState="checkClientOnHold",cond=whenDispatch("cleantableok"))
					transition(edgeName="t057",targetState="checkTableAvail",cond=whenRequest("table"))
					transition(edgeName="t058",targetState="reach",cond=whenDispatch("clientatentrance"))
					transition(edgeName="t059",targetState="takeOrder",cond=whenDispatch("placeorder"))
					transition(edgeName="t060",targetState="serveOrder",cond=whenReply("orderready"))
					transition(edgeName="t061",targetState="getPayment",cond=whenDispatch("payment"))
					transition(edgeName="t062",targetState="doClean",cond=whenDispatch("cleantable"))
				}	 
				state("checkClientOnHold") { //this:State
					action { //it:State
						solve("client(Cid,onhold)","") //set resVar	
						if( currentSolution.isSuccess() ) { val OnHoldCid = getCurSol("Cid").toString()  
						solve("retract(client($OnHoldCid,onhold))","") //set resVar	
						solve("reserveTable(N,$OnHoldCid)","") //set resVar	
						if( currentSolution.isSuccess() ) {solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
						forward("clientatentrance", "clientatentrance($OnHoldCid)" ,"waiter" ) 
						}
						else
						{}
						solve("teatable(Num,free,dirty)","") //set resVar	
						if( currentSolution.isSuccess() ) { val TableNum = getCurSol("Num").toString()  
						forward("cleantable", "cleantable($TableNum)" ,"waiter" ) 
						}
						else
						{}
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("checkDirtyTable") { //this:State
					action { //it:State
						 var TableNum = ""  
						solve("teatable(Num,free,dirty)","") //set resVar	
						if( currentSolution.isSuccess() ) { TableNum = getCurSol("Num").toString()  
						}
						else
						{}
						solve("teatable(Num,free,cleanedA)","") //set resVar	
						if( currentSolution.isSuccess() ) { TableNum = getCurSol("Num").toString()  
						}
						else
						{}
						solve("teatable(Num,free,cleanedB)","") //set resVar	
						if( currentSolution.isSuccess() ) { TableNum = getCurSol("Num").toString()  
						}
						else
						{}
						if(  TableNum != ""  
						 ){forward("cleantable", "cleantable($TableNum)" ,"waiter" ) 
						}
						stateTimer = TimerActor("timer_checkDirtyTable", 
							scope, context!!, "local_tout_waiter_checkDirtyTable", RestWaitTime )
					}
					 transition(edgeName="t063",targetState="rest",cond=whenTimeout("local_tout_waiter_checkDirtyTable"))   
					transition(edgeName="t064",targetState="thinkCleanTable",cond=whenDispatch("cleantable"))
					transition(edgeName="t065",targetState="reach",cond=whenDispatch("clientatentrance"))
					transition(edgeName="t066",targetState="takeOrder",cond=whenDispatch("placeorder"))
					transition(edgeName="t067",targetState="serveOrder",cond=whenReply("orderready"))
					transition(edgeName="t068",targetState="getPayment",cond=whenDispatch("payment"))
				}	 
				state("rest") { //this:State
					action { //it:State
						solve("updateWaiterState(X,gorest(home))","") //set resVar	
						solve("coordinatesTo(home,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()		 
						request("moveTo", "moveTo($X,$Y)" ,"robot" )  
						}
						else
						{}
					}
					 transition(edgeName="t069",targetState="atHome",cond=whenReply("moveOk"))
					transition(edgeName="t070",targetState="rest",cond=whenReply("moveKo"))
					transition(edgeName="t071",targetState="cancelCurrentPlan",cond=whenRequest("table"))
					transition(edgeName="t072",targetState="cancelCurrentPlan",cond=whenDispatch("clientatentrance"))
					transition(edgeName="t073",targetState="cancelCurrentPlan",cond=whenDispatch("placeorder"))
					transition(edgeName="t074",targetState="cancelCurrentPlan",cond=whenReply("orderready"))
					transition(edgeName="t075",targetState="cancelCurrentPlan",cond=whenDispatch("payment"))
					transition(edgeName="t076",targetState="thinkCleanTable",cond=whenDispatch("cleantable"))
				}	 
				state("atHome") { //this:State
					action { //it:State
						solve("updateWaiterState(X,rest(0))","") //set resVar	
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
			}
		}
}
