/* Generated by AN DISI Unibo */ 
package it.unibo.waiter

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Waiter ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val MaxStayTime 	= 100000L	
				val DelayTime 		= 1000L
				val RestWaitTime 	= 10000L
				var CurrentCid		= ""
				
				var TeatableFree	= true
				var IsWaiterAtHome  = true
				var Moving = false
				
				var Debug = true
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = false
						solve("consult('tearoomKB-PA-sprint2.pl')","") //set resVar	
						solve("debug(true)","") //set resVar	
						if( currentSolution.isSuccess() ) { Debug = true  
						}
						else
						{}
						println("waiter starting, debug is $Debug")
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("waitState") { //this:State
					action { //it:State
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
						if(Debug) 
						println(getCurSol("S").toString())
						solve("waiter(_,0,0)","") //set resVar	
						if( currentSolution.isSuccess() ) { IsWaiterAtHome = true  
						}
						else
						{ IsWaiterAtHome = false  
						}
						stateTimer = TimerActor("timer_waitState", 
							scope, context!!, "local_tout_waiter_waitState", RestWaitTime )
					}
					 transition(edgeName="t011",targetState="maybeRest",cond=whenTimeout("local_tout_waiter_waitState"))   
					transition(edgeName="t012",targetState="checkTableAvail",cond=whenRequest("table"))
					transition(edgeName="t013",targetState="reach",cond=whenDispatch("clientatentrance"))
					transition(edgeName="t014",targetState="takeOrder",cond=whenDispatch("placeorder"))
					transition(edgeName="t015",targetState="serveOrder",cond=whenReply("orderready"))
					transition(edgeName="t016",targetState="getPayment",cond=whenDispatch("payment"))
					transition(edgeName="t017",targetState="thinkCleanTable",cond=whenDispatch("cleantable"))
				}	 
				state("checkTableAvail") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter checkTableAvail")
						if(  Moving  
						 ){ Moving = false  
						forward("stopPlan", "stopPlan(0)" ,"robot" ) 
						}
						if( checkMsgContent( Term.createTerm("table(CID)"), Term.createTerm("table(Cid)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentCid = payloadArg(0)  
								solve("updateWaiterState(X,checkAvailability($CurrentCid))","") //set resVar	
								solve("occupyHall($CurrentCid)","") //set resVar	
								solve("reserveTable(Num,$CurrentCid)","") //set resVar	
								if( currentSolution.isSuccess() ) {answer("table", "available", "available($CurrentCid)"   )  
								forward("clientatentrance", "clientatentrance($CurrentCid)" ,"waiter" ) 
								}
								else
								{forward("clientonhold", "clientonhold($CurrentCid)" ,"waiter" ) 
								answer("table", "full", "full($CurrentCid,$MaxStayTime)"   )  
								solve("assert(client($CurrentCid,onhold))","") //set resVar	
								}
						}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
						if(Debug) 
						println(getCurSol("S").toString())
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("reach") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter reach")
						if(  Moving  
						 ){ Moving = false  
						forward("stopPlan", "stopPlan(0)" ,"robot" ) 
						}
						if( checkMsgContent( Term.createTerm("clientatentrance(Cid)"), Term.createTerm("clientatentrance(CurrentCid)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentCid = payloadArg(0)  
								solve("updateWaiterState(X,reach($CurrentCid))","") //set resVar	
						}
						if( checkMsgContent( Term.createTerm("moveKo(X,Y)"), Term.createTerm("moveKo(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								solve("updateWaiterLoc(A,$X,$Y)","") //set resVar	
						}
						solve("coordinatesTo(entrancedoor,OldX,OldY,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val OldX = getCurSol("OldX").toString()
										val OldY = getCurSol("OldY").toString()
										val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()		 
						request("moveTo", "moveTo($OldX,$OldY,$X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
						if(Debug) 
						println(getCurSol("S").toString())
					}
					 transition(edgeName="t018",targetState="reachp2",cond=whenReply("moveOk"))
					transition(edgeName="t019",targetState="reach",cond=whenReply("moveKo"))
				}	 
				state("reachp2") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter reachp2")
						if( checkMsgContent( Term.createTerm("moveKo(X,Y)"), Term.createTerm("moveKo(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								solve("updateWaiterLoc(_,$X,$Y)","") //set resVar	
						}
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("freeHall($CurrentCid)","") //set resVar	
								solve("updateClient($CurrentCid,entering)","") //set resVar	
								solve("updateWaiterLoc(entrancedoor,X,Y)","") //set resVar	
								solve("updateWaiterState(X,at(entrancedoor))","") //set resVar	
						}
						solve("teatable(Num,reserved($CurrentCid),clean)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("coordinatesTo(teatable($TableNum),OldX,OldY,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val OldX = getCurSol("OldX").toString()
										val OldY = getCurSol("OldY").toString()
										val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()		 
						request("moveTo", "moveTo($OldX,$OldY,$X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition(edgeName="t020",targetState="reachp3",cond=whenReply("moveOk"))
					transition(edgeName="t021",targetState="reachp2",cond=whenReply("moveKo"))
				}	 
				state("reachp3") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter reachp3")
						solve("teatable(Num,reserved($CurrentCid),clean)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("updateWaiterState(X,deployed($CurrentCid,$TableNum))","") //set resVar	
						solve("updateWaiterLoc(teatable($TableNum),X,Y)","") //set resVar	
						solve("engageTable($TableNum,$CurrentCid)","") //set resVar	
						emit("attable", "attable($CurrentCid)" ) 
						solve("updateClient($CurrentCid,choosing)","") //set resVar	
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("takeOrder") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter takeOrder")
						if(  Moving  
						 ){ Moving = false  
						forward("stopPlan", "stopPlan(0)" ,"robot" ) 
						}
						if( checkMsgContent( Term.createTerm("moveKo(X,Y)"), Term.createTerm("moveKo(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								solve("updateWaiterLoc(S,$X,$Y)","") //set resVar	
						}
						if( checkMsgContent( Term.createTerm("placeorder(CID)"), Term.createTerm("placeorder(CurrentCid)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentCid = payloadArg(0)  
								solve("updateWaiterState(X,goTakeOrder($CurrentCid))","") //set resVar	
								solve("updateClient($CurrentCid,placeorder)","") //set resVar	
						}
						solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("coordinatesTo(teatable($TableNum),OldX,OldY,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val OldX = getCurSol("OldX").toString()
										val OldY = getCurSol("OldY").toString()
										val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()		 
						request("moveTo", "moveTo($OldX,$OldY,$X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition(edgeName="t022",targetState="takeOrderp2",cond=whenReply("moveOk"))
					transition(edgeName="t023",targetState="takeOrder",cond=whenReply("moveKo"))
				}	 
				state("takeOrderp2") { //this:State
					action { //it:State
						solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("updateWaiterLoc(teatable($TableNum),X,Y)","") //set resVar	
						solve("updateWaiterState(X,takingOrder($CurrentCid))","") //set resVar	
						solve("updateClient($CurrentCid,orderplaced)","") //set resVar	
						request("relayorder", "relayorder($CurrentCid)" ,"barman" )  
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("serveOrder") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter serveOrder")
						if(  Moving  
						 ){ Moving = false  
						forward("stopPlan", "stopPlan(0)" ,"robot" ) 
						}
						if( checkMsgContent( Term.createTerm("orderready(Cid)"), Term.createTerm("orderready(CurrentCid)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentCid = payloadArg(0)  
								solve("updateWaiterState(X,getOrder($CurrentCid))","") //set resVar	
						}
						if( checkMsgContent( Term.createTerm("moveKo(X,Y)"), Term.createTerm("moveKo(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								solve("updateWaiterLoc(S,$X,$Y)","") //set resVar	
						}
						solve("coordinatesTo(barman,OldX,OldY,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val OldX = getCurSol("OldX").toString()
										val OldY = getCurSol("OldY").toString()
										val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()	 
						request("moveTo", "moveTo($OldX,$OldY,$X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition(edgeName="t024",targetState="serveOrderp2",cond=whenReply("moveOk"))
					transition(edgeName="t025",targetState="serveOrder",cond=whenReply("moveKo"))
				}	 
				state("serveOrderp2") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveKo(X,Y)"), Term.createTerm("moveKo(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								solve("updateWaiterLoc(_,$X,$Y)","") //set resVar	
						}
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("updateWaiterState(X,bar($CurrentCid))","") //set resVar	
								solve("updateWaiterLoc(barman,X,Y)","") //set resVar	
						}
						solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("coordinatesTo(teatable($TableNum),OldX,OldY,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val OldX = getCurSol("OldX").toString()
										val OldY = getCurSol("OldY").toString()
										val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()  
						request("moveTo", "moveTo($OldX,$OldY,$X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition(edgeName="t026",targetState="serveOrderp3",cond=whenReply("moveOk"))
					transition(edgeName="t027",targetState="serveOrderp2",cond=whenReply("moveKo"))
				}	 
				state("serveOrderp3") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
								  val X = payloadArg(0)
												val Y = payloadArg(1)   
												val TableNum = getCurSol("Num").toString()	 
								solve("updateWaiterLoc(teatable($TableNum),$X,$Y)","") //set resVar	
								solve("updateWaiterState(X,serving($CurrentCid))","") //set resVar	
								solve("updateClient($CurrentCid,consuming)","") //set resVar	
								emit("delivered", "delivered($CurrentCid)" ) 
						}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						if(Debug) 
						println(getCurSol("S").toString())
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("getPayment") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter getPayment")
						if(  Moving  
						 ){ Moving = false  
						forward("stopPlan", "stopPlan(0)" ,"robot" ) 
						}
						if( checkMsgContent( Term.createTerm("payment(Cid)"), Term.createTerm("payment(CurrentCid)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentCid = payloadArg(0)  
								solve("updateWaiterState(X,getPayment($CurrentCid))","") //set resVar	
						}
						if( checkMsgContent( Term.createTerm("moveKo(X,Y)"), Term.createTerm("moveKo(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								solve("updateWaiterLoc(_,$X,$Y)","") //set resVar	
						}
						solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
						 val TableNum = getCurSol("Num").toString()  
						solve("coordinatesTo(teatable($TableNum),OldX,OldY,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val OldX = getCurSol("OldX").toString()
										val OldY = getCurSol("OldY").toString()
										val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()		 
						request("moveTo", "moveTo($OldX,$OldY,$X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition(edgeName="t028",targetState="getPaymentp2",cond=whenReply("moveOk"))
					transition(edgeName="t029",targetState="getPayment",cond=whenReply("moveKo"))
				}	 
				state("getPaymentp2") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("teatable(Num,busy($CurrentCid),dirty)","") //set resVar	
								 val TableNum = getCurSol("Num").toString()  
								solve("updateWaiterState(X,paymentatteatable($TableNum))","") //set resVar	
								solve("updateWaiterLoc(teatable($TableNum),X,Y)","") //set resVar	
								solve("updateClient($CurrentCid,paying)","") //set resVar	
								delay(2000) 
								solve("freeTable($TableNum,$CurrentCid)","") //set resVar	
								emit("paymentOk", "paymentOk($CurrentCid)" ) 
								solve("updateClient($CurrentCid,leaving)","") //set resVar	
								forward("cleantable", "cleantable($TableNum)" ,"waiter" ) 
						}
						if( checkMsgContent( Term.createTerm("moveKo(X,Y)"), Term.createTerm("moveKo(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								solve("updateWaiterLoc(_,$X,$Y)","") //set resVar	
								solve("updateClient($CurrentCid,leaving)","") //set resVar	
						}
						solve("coordinatesTo(exitdoor,OldX,OldY,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  
										val OldX = getCurSol("OldX").toString()
										val OldY = getCurSol("OldY").toString()
										val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()
						request("moveTo", "moveTo($OldX,$OldY,$X,$Y)" ,"robot" )  
						}
						else
						{}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition(edgeName="t030",targetState="escortToExit",cond=whenReply("moveOk"))
					transition(edgeName="t031",targetState="getPaymentp2",cond=whenReply("moveKo"))
				}	 
				state("escortToExit") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								emit("exitOk", "exitOk($CurrentCid)" ) 
								solve("updateWaiterLoc(at(exitdoor),$X,$Y)","") //set resVar	
								solve("updateWaiterState(X,at(exitdoor))","") //set resVar	
								solve("updateClient($CurrentCid,left)","") //set resVar	
						}
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("thinkCleanTable") { //this:State
					action { //it:State
						 Moving = true  
						if( checkMsgContent( Term.createTerm("cleantable(Num)"), Term.createTerm("cleantable(Num)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val TableNum = payloadArg(0)  
								solve("updateWaiterState(X,gocleanteatable($TableNum))","") //set resVar	
								solve("coordinatesTo(teatable($TableNum),OldX,OldY,X,Y)","") //set resVar	
								if( currentSolution.isSuccess() ) {  val OldX = getCurSol("OldX").toString()
												val OldY = getCurSol("OldY").toString()
												val X = getCurSol("X").toString()
												val Y = getCurSol("Y").toString()		 
								request("moveTo", "moveTo($OldX,$OldY,$X,$Y)" ,"robot" )  
								}
								else
								{}
						}
					}
					 transition(edgeName="t032",targetState="cleanTable",cond=whenReply("moveOk"))
					transition(edgeName="t033",targetState="thinkCleanTable",cond=whenReply("moveKo"))
					transition(edgeName="t034",targetState="checkTableAvail",cond=whenRequest("table"))
					transition(edgeName="t035",targetState="reach",cond=whenDispatch("clientatentrance"))
					transition(edgeName="t036",targetState="takeOrder",cond=whenDispatch("placeorder"))
					transition(edgeName="t037",targetState="serveOrder",cond=whenReply("orderready"))
					transition(edgeName="t038",targetState="getPayment",cond=whenDispatch("payment"))
				}	 
				state("cleanTable") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter cleanTable")
						if( checkMsgContent( Term.createTerm("moveOk(X,Y)"), Term.createTerm("moveOk(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								solve("updateWaiterLoc(teatable(Num),$X,$Y)","") //set resVar	
								 val TableNum = getCurSol("Num").toString()  
								solve("updateWaiterState(X,atteatable($TableNum))","") //set resVar	
								solve("roomstate(S)","") //set resVar	
								if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
								)
								}
								else
								{}
						}
						stateTimer = TimerActor("timer_cleanTable", 
							scope, context!!, "local_tout_waiter_cleanTable", 100.toLong() )
					}
					 transition(edgeName="t039",targetState="doClean",cond=whenTimeout("local_tout_waiter_cleanTable"))   
					transition(edgeName="t040",targetState="checkTableAvail",cond=whenRequest("table"))
					transition(edgeName="t041",targetState="reach",cond=whenDispatch("clientatentrance"))
					transition(edgeName="t042",targetState="takeOrder",cond=whenDispatch("placeorder"))
					transition(edgeName="t043",targetState="serveOrder",cond=whenReply("orderready"))
					transition(edgeName="t044",targetState="getPayment",cond=whenDispatch("payment"))
				}	 
				state("doClean") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter doClean")
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {println(getCurSol("S").toString())
						}
						else
						{}
						solve("updateWaiterState(atteatable(TableNum),cleaning(TableNum))","") //set resVar	
						 val TableNum = getCurSol("TableNum").toString()  
						delay(DelayTime)
						solve("cleanTable($TableNum)","") //set resVar	
						solve("updateWaiterState(X,cleaned($TableNum))","") //set resVar	
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="checkClientOnHold", cond=doswitch() )
				}	 
				state("checkClientOnHold") { //this:State
					action { //it:State
						if(Debug) 
						println("table cleaned letting somebody in")
						 if(Debug)  
						solve("clients(L)","") //set resVar	
						 if(Debug) println("clients are: ${getCurSol("L").toString()}")  
						solve("client(Cid,onhold)","") //set resVar	
						if( currentSolution.isSuccess() ) { val OnHoldCid = getCurSol("Cid").toString()  
						 if(Debug)println("ok, client waiting is num: $OnHoldCid")  
						if(  Debug  
						 ){solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) { println("------------------------------------pre solves ${getCurSol("S").toString()}")  
						}
						else
						{}
						}
						solve("retract(client($OnHoldCid,onhold))","") //set resVar	
						solve("reserveTable(N,$OnHoldCid)","") //set resVar	
						if( currentSolution.isSuccess() ) {solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
						if(Debug) println("DEBUG ---------- sending clientatantrence($OnHoldCid)  ------------")  
						forward("clientatentrance", "clientatentrance($OnHoldCid)" ,"waiter" ) 
						}
						else
						{}
						if(  Debug  
						 ){solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) { println("------------------------------------post solves ${getCurSol("S").toString()}")  
						}
						else
						{}
						}
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
				state("maybeRest") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitchGuarded({ IsWaiterAtHome  
					}) )
					transition( edgeName="goto",targetState="rest", cond=doswitchGuarded({! ( IsWaiterAtHome  
					) }) )
				}	 
				state("rest") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter rest")
						 Moving = true  
						if( checkMsgContent( Term.createTerm("moveKo(X,Y)"), Term.createTerm("moveKo(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val X = payloadArg(0)
												val Y = payloadArg(1)    
								solve("updateWaiterLoc(_,$X,$Y)","") //set resVar	
								solve("roomstate(S)","") //set resVar	
								if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
								)
								}
								else
								{}
						}
						solve("coordinatesTo(home,OldX,OldY,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) {  val OldX = getCurSol("OldX").toString()
										val OldY = getCurSol("OldY").toString()
										val X = getCurSol("X").toString()
										val Y = getCurSol("Y").toString()		 
						request("moveTo", "moveTo($OldX,$OldY,$X,$Y)" ,"robot" )  
						}
						else
						{}
					}
					 transition(edgeName="t045",targetState="atHome",cond=whenReply("moveOk"))
					transition(edgeName="t046",targetState="rest",cond=whenReply("moveKo"))
					transition(edgeName="t047",targetState="checkTableAvail",cond=whenRequest("table"))
					transition(edgeName="t048",targetState="reach",cond=whenDispatch("clientatentrance"))
					transition(edgeName="t049",targetState="takeOrder",cond=whenDispatch("placeorder"))
					transition(edgeName="t050",targetState="serveOrder",cond=whenReply("orderready"))
					transition(edgeName="t051",targetState="getPayment",cond=whenDispatch("payment"))
				}	 
				state("atHome") { //this:State
					action { //it:State
						if(Debug) 
						println("waiter athome")
						solve("updateWaiterState(X,rest)","") //set resVar	
						solve("updateWaiterLoc(home,X,Y)","") //set resVar	
						solve("roomstate(S)","") //set resVar	
						if( currentSolution.isSuccess() ) {updateResourceRep( getCurSol("S").toString()  
						)
						}
						else
						{}
					}
					 transition( edgeName="goto",targetState="waitState", cond=doswitch() )
				}	 
			}
		}
}
